version: '3.8'

x-env_file:
  &env_file
  - .env

services:
  backend:
    image: python:3.8
    env_file:
      *env_file
    volumes:
      - ./:/code
    init: true
    command: ['sleep', '365d']

  nginx:
    image: nginx:1.18-alpine
    ports:
      - '${NGINX_PORT}:80'
